package com.cms.pojo;

import java.util.Date;

public class TbCollateralContent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collateral_content.id
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collateral_content.name
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collateral_content.parent_id
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collateral_content.is_parent
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    private String isParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collateral_content.sortno
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    private String sortno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collateral_content.table_name
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collateral_content.status
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collateral_content.create_user
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collateral_content.create_org
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    private String createOrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collateral_content.create_time
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collateral_content.update_user
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collateral_content.update_org
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    private String updateOrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collateral_content.update_time
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collateral_content.remark
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collateral_content.id
     *
     * @return the value of tb_collateral_content.id
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collateral_content.id
     *
     * @param id the value for tb_collateral_content.id
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collateral_content.name
     *
     * @return the value of tb_collateral_content.name
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collateral_content.name
     *
     * @param name the value for tb_collateral_content.name
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collateral_content.parent_id
     *
     * @return the value of tb_collateral_content.parent_id
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collateral_content.parent_id
     *
     * @param parentId the value for tb_collateral_content.parent_id
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collateral_content.is_parent
     *
     * @return the value of tb_collateral_content.is_parent
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public String getIsParent() {
        return isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collateral_content.is_parent
     *
     * @param isParent the value for tb_collateral_content.is_parent
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public void setIsParent(String isParent) {
        this.isParent = isParent == null ? null : isParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collateral_content.sortno
     *
     * @return the value of tb_collateral_content.sortno
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public String getSortno() {
        return sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collateral_content.sortno
     *
     * @param sortno the value for tb_collateral_content.sortno
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public void setSortno(String sortno) {
        this.sortno = sortno == null ? null : sortno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collateral_content.table_name
     *
     * @return the value of tb_collateral_content.table_name
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collateral_content.table_name
     *
     * @param tableName the value for tb_collateral_content.table_name
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collateral_content.status
     *
     * @return the value of tb_collateral_content.status
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collateral_content.status
     *
     * @param status the value for tb_collateral_content.status
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collateral_content.create_user
     *
     * @return the value of tb_collateral_content.create_user
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collateral_content.create_user
     *
     * @param createUser the value for tb_collateral_content.create_user
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collateral_content.create_org
     *
     * @return the value of tb_collateral_content.create_org
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public String getCreateOrg() {
        return createOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collateral_content.create_org
     *
     * @param createOrg the value for tb_collateral_content.create_org
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public void setCreateOrg(String createOrg) {
        this.createOrg = createOrg == null ? null : createOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collateral_content.create_time
     *
     * @return the value of tb_collateral_content.create_time
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collateral_content.create_time
     *
     * @param createTime the value for tb_collateral_content.create_time
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collateral_content.update_user
     *
     * @return the value of tb_collateral_content.update_user
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collateral_content.update_user
     *
     * @param updateUser the value for tb_collateral_content.update_user
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collateral_content.update_org
     *
     * @return the value of tb_collateral_content.update_org
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public String getUpdateOrg() {
        return updateOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collateral_content.update_org
     *
     * @param updateOrg the value for tb_collateral_content.update_org
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public void setUpdateOrg(String updateOrg) {
        this.updateOrg = updateOrg == null ? null : updateOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collateral_content.update_time
     *
     * @return the value of tb_collateral_content.update_time
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collateral_content.update_time
     *
     * @param updateTime the value for tb_collateral_content.update_time
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collateral_content.remark
     *
     * @return the value of tb_collateral_content.remark
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collateral_content.remark
     *
     * @param remark the value for tb_collateral_content.remark
     *
     * @mbg.generated Wed Jun 20 21:40:08 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}