package com.cms.pojo;

public class TbMenuInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu_info.menu_id
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu_info.menu_name
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu_info.parent_id
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu_info.is_parent
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    private String isParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu_info.sortno
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    private String sortno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu_info.status
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu_info.url
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu_info.param
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    private String param;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu_info.menu_id
     *
     * @return the value of tb_menu_info.menu_id
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu_info.menu_id
     *
     * @param menuId the value for tb_menu_info.menu_id
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu_info.menu_name
     *
     * @return the value of tb_menu_info.menu_name
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu_info.menu_name
     *
     * @param menuName the value for tb_menu_info.menu_name
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu_info.parent_id
     *
     * @return the value of tb_menu_info.parent_id
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu_info.parent_id
     *
     * @param parentId the value for tb_menu_info.parent_id
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu_info.is_parent
     *
     * @return the value of tb_menu_info.is_parent
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    public String getIsParent() {
        return isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu_info.is_parent
     *
     * @param isParent the value for tb_menu_info.is_parent
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    public void setIsParent(String isParent) {
        this.isParent = isParent == null ? null : isParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu_info.sortno
     *
     * @return the value of tb_menu_info.sortno
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    public String getSortno() {
        return sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu_info.sortno
     *
     * @param sortno the value for tb_menu_info.sortno
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    public void setSortno(String sortno) {
        this.sortno = sortno == null ? null : sortno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu_info.status
     *
     * @return the value of tb_menu_info.status
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu_info.status
     *
     * @param status the value for tb_menu_info.status
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu_info.url
     *
     * @return the value of tb_menu_info.url
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu_info.url
     *
     * @param url the value for tb_menu_info.url
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu_info.param
     *
     * @return the value of tb_menu_info.param
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu_info.param
     *
     * @param param the value for tb_menu_info.param
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }
}