package com.cms.pojo;

import java.util.Date;

public class TbUserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.id
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.loginid
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    private String loginid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.username
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.password
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.orgid
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    private Short orgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.birthdat
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    private Date birthdat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.gender
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.telphone
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    private String telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.mobilephone
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    private Short mobilephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.email
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.address
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.image
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.inputuserid
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    private Byte inputuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.inputorgid
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    private Short inputorgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.inputdate
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    private Date inputdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.updateuserid
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    private Byte updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.updateorgid
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    private Short updateorgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.updatedate
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    private Date updatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.lasttime
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    private Date lasttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.language
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.theme
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    private String theme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.remark
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.id
     *
     * @return the value of tb_user_info.id
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.id
     *
     * @param id the value for tb_user_info.id
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.loginid
     *
     * @return the value of tb_user_info.loginid
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public String getLoginid() {
        return loginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.loginid
     *
     * @param loginid the value for tb_user_info.loginid
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public void setLoginid(String loginid) {
        this.loginid = loginid == null ? null : loginid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.username
     *
     * @return the value of tb_user_info.username
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.username
     *
     * @param username the value for tb_user_info.username
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.password
     *
     * @return the value of tb_user_info.password
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.password
     *
     * @param password the value for tb_user_info.password
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.orgid
     *
     * @return the value of tb_user_info.orgid
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public Short getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.orgid
     *
     * @param orgid the value for tb_user_info.orgid
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public void setOrgid(Short orgid) {
        this.orgid = orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.birthdat
     *
     * @return the value of tb_user_info.birthdat
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public Date getBirthdat() {
        return birthdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.birthdat
     *
     * @param birthdat the value for tb_user_info.birthdat
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public void setBirthdat(Date birthdat) {
        this.birthdat = birthdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.gender
     *
     * @return the value of tb_user_info.gender
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.gender
     *
     * @param gender the value for tb_user_info.gender
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.telphone
     *
     * @return the value of tb_user_info.telphone
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.telphone
     *
     * @param telphone the value for tb_user_info.telphone
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.mobilephone
     *
     * @return the value of tb_user_info.mobilephone
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public Short getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.mobilephone
     *
     * @param mobilephone the value for tb_user_info.mobilephone
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public void setMobilephone(Short mobilephone) {
        this.mobilephone = mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.email
     *
     * @return the value of tb_user_info.email
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.email
     *
     * @param email the value for tb_user_info.email
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.address
     *
     * @return the value of tb_user_info.address
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.address
     *
     * @param address the value for tb_user_info.address
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.image
     *
     * @return the value of tb_user_info.image
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.image
     *
     * @param image the value for tb_user_info.image
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.inputuserid
     *
     * @return the value of tb_user_info.inputuserid
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public Byte getInputuserid() {
        return inputuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.inputuserid
     *
     * @param inputuserid the value for tb_user_info.inputuserid
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public void setInputuserid(Byte inputuserid) {
        this.inputuserid = inputuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.inputorgid
     *
     * @return the value of tb_user_info.inputorgid
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public Short getInputorgid() {
        return inputorgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.inputorgid
     *
     * @param inputorgid the value for tb_user_info.inputorgid
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public void setInputorgid(Short inputorgid) {
        this.inputorgid = inputorgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.inputdate
     *
     * @return the value of tb_user_info.inputdate
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public Date getInputdate() {
        return inputdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.inputdate
     *
     * @param inputdate the value for tb_user_info.inputdate
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public void setInputdate(Date inputdate) {
        this.inputdate = inputdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.updateuserid
     *
     * @return the value of tb_user_info.updateuserid
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public Byte getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.updateuserid
     *
     * @param updateuserid the value for tb_user_info.updateuserid
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public void setUpdateuserid(Byte updateuserid) {
        this.updateuserid = updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.updateorgid
     *
     * @return the value of tb_user_info.updateorgid
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public Short getUpdateorgid() {
        return updateorgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.updateorgid
     *
     * @param updateorgid the value for tb_user_info.updateorgid
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public void setUpdateorgid(Short updateorgid) {
        this.updateorgid = updateorgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.updatedate
     *
     * @return the value of tb_user_info.updatedate
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.updatedate
     *
     * @param updatedate the value for tb_user_info.updatedate
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.lasttime
     *
     * @return the value of tb_user_info.lasttime
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public Date getLasttime() {
        return lasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.lasttime
     *
     * @param lasttime the value for tb_user_info.lasttime
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public void setLasttime(Date lasttime) {
        this.lasttime = lasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.language
     *
     * @return the value of tb_user_info.language
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.language
     *
     * @param language the value for tb_user_info.language
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.theme
     *
     * @return the value of tb_user_info.theme
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.theme
     *
     * @param theme the value for tb_user_info.theme
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.remark
     *
     * @return the value of tb_user_info.remark
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.remark
     *
     * @param remark the value for tb_user_info.remark
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}