package com.cms.pojo;

import java.util.Date;

public class TbUserInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.user_id
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.login_id
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private String loginId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.user_name
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.password
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.org_id
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private String orgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.status
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.birthday
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.gender
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private Byte gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.telphone
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private String telphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.mobilephone
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private String mobilephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.email
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.address
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.image
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private String image;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.create_user
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.create_org
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private String createOrg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.create_date
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.update_user
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private Byte updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.update_org
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private Short updateOrg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.update_date
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.last_time
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private Date lastTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.language
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private String language;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.theme
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private String theme;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.remark
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.user_id
	 * @return  the value of tb_user_info.user_id
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.user_id
	 * @param userId  the value for tb_user_info.user_id
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.login_id
	 * @return  the value of tb_user_info.login_id
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public String getLoginId() {
		return loginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.login_id
	 * @param loginId  the value for tb_user_info.login_id
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setLoginId(String loginId) {
		this.loginId = loginId == null ? null : loginId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.user_name
	 * @return  the value of tb_user_info.user_name
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.user_name
	 * @param userName  the value for tb_user_info.user_name
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.password
	 * @return  the value of tb_user_info.password
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.password
	 * @param password  the value for tb_user_info.password
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.org_id
	 * @return  the value of tb_user_info.org_id
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public String getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.org_id
	 * @param orgId  the value for tb_user_info.org_id
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setOrgId(String orgId) {
		this.orgId = orgId == null ? null : orgId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.status
	 * @return  the value of tb_user_info.status
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.status
	 * @param status  the value for tb_user_info.status
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.birthday
	 * @return  the value of tb_user_info.birthday
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.birthday
	 * @param birthday  the value for tb_user_info.birthday
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.gender
	 * @return  the value of tb_user_info.gender
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public Byte getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.gender
	 * @param gender  the value for tb_user_info.gender
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setGender(Byte gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.telphone
	 * @return  the value of tb_user_info.telphone
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public String getTelphone() {
		return telphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.telphone
	 * @param telphone  the value for tb_user_info.telphone
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setTelphone(String telphone) {
		this.telphone = telphone == null ? null : telphone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.mobilephone
	 * @return  the value of tb_user_info.mobilephone
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public String getMobilephone() {
		return mobilephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.mobilephone
	 * @param mobilephone  the value for tb_user_info.mobilephone
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setMobilephone(String mobilephone) {
		this.mobilephone = mobilephone == null ? null : mobilephone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.email
	 * @return  the value of tb_user_info.email
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.email
	 * @param email  the value for tb_user_info.email
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.address
	 * @return  the value of tb_user_info.address
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.address
	 * @param address  the value for tb_user_info.address
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.image
	 * @return  the value of tb_user_info.image
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public String getImage() {
		return image;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.image
	 * @param image  the value for tb_user_info.image
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setImage(String image) {
		this.image = image == null ? null : image.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.create_user
	 * @return  the value of tb_user_info.create_user
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.create_user
	 * @param createUser  the value for tb_user_info.create_user
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser == null ? null : createUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.create_org
	 * @return  the value of tb_user_info.create_org
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public String getCreateOrg() {
		return createOrg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.create_org
	 * @param createOrg  the value for tb_user_info.create_org
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setCreateOrg(String createOrg) {
		this.createOrg = createOrg == null ? null : createOrg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.create_date
	 * @return  the value of tb_user_info.create_date
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.create_date
	 * @param createDate  the value for tb_user_info.create_date
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.update_user
	 * @return  the value of tb_user_info.update_user
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public Byte getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.update_user
	 * @param updateUser  the value for tb_user_info.update_user
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setUpdateUser(Byte updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.update_org
	 * @return  the value of tb_user_info.update_org
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public Short getUpdateOrg() {
		return updateOrg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.update_org
	 * @param updateOrg  the value for tb_user_info.update_org
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setUpdateOrg(Short updateOrg) {
		this.updateOrg = updateOrg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.update_date
	 * @return  the value of tb_user_info.update_date
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.update_date
	 * @param updateDate  the value for tb_user_info.update_date
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.last_time
	 * @return  the value of tb_user_info.last_time
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public Date getLastTime() {
		return lastTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.last_time
	 * @param lastTime  the value for tb_user_info.last_time
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setLastTime(Date lastTime) {
		this.lastTime = lastTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.language
	 * @return  the value of tb_user_info.language
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public String getLanguage() {
		return language;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.language
	 * @param language  the value for tb_user_info.language
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setLanguage(String language) {
		this.language = language == null ? null : language.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.theme
	 * @return  the value of tb_user_info.theme
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public String getTheme() {
		return theme;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.theme
	 * @param theme  the value for tb_user_info.theme
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setTheme(String theme) {
		this.theme = theme == null ? null : theme.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.remark
	 * @return  the value of tb_user_info.remark
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.remark
	 * @param remark  the value for tb_user_info.remark
	 * @mbg.generated  Sun Jun 17 21:46:16 CST 2018
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}