package com.cms.dao;

import com.cms.pojo.TbMenuInfo;
import com.cms.pojo.TbMenuInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbMenuInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    long countByExample(TbMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    int deleteByExample(TbMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    int deleteByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    int insert(TbMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    int insertSelective(TbMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    List<TbMenuInfo> selectByExample(TbMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    TbMenuInfo selectByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbMenuInfo record, @Param("example") TbMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    int updateByExample(@Param("record") TbMenuInfo record, @Param("example") TbMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    int updateByPrimaryKeySelective(TbMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbg.generated Mon Jun 18 00:03:33 CST 2018
     */
    int updateByPrimaryKey(TbMenuInfo record);
}