package com.cms.dao;

import com.cms.pojo.TbUserInfo;
import com.cms.pojo.TbUserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_info
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    long countByExample(TbUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_info
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    int deleteByExample(TbUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_info
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_info
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    int insert(TbUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_info
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    int insertSelective(TbUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_info
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    List<TbUserInfo> selectByExample(TbUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_info
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    TbUserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_info
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbUserInfo record, @Param("example") TbUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_info
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    int updateByExample(@Param("record") TbUserInfo record, @Param("example") TbUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_info
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    int updateByPrimaryKeySelective(TbUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_info
     *
     * @mbg.generated Mon Jun 11 00:38:00 CST 2018
     */
    int updateByPrimaryKey(TbUserInfo record);
}